### ISSUE TITLE
5.1.4_`infer`를 활용하여 타입을 만들어보세요.

### ISSUE THREAD

**Issue by Stilllee** [Coding-Village-Protector/woowahan-ts#12]
📝 p156

❓`infer`를 사용하여, 배열의 요소 타입을 추론하는 `ElementType` 타입을 만들어 보세요.
- `ElementType` 타입은 배열을 입력으로 받아 그 배열의 요소 타입을 추론해야 합니다.
- 배열이 아닌 타입이 입력으로 주어지면, `never` 타입을 반환해야 합니다.
```ts
type ElementType<T> = /* 여기에 구현하세요 */;

const numberArray = [1, 2, 3];
const stringArray = ["a", "b", "c"];

type NumberElementType = ElementType<typeof numberArray>; // 'number' 타입이 되어야 함
type StringElementType = ElementType<typeof stringArray>; // 'string' 타입이 되어야 함
```

**Comment by lulla-by** [comment]
infer를 사용해서 U를 추론하고 이 U로 이루어진 배열이 아닌 타입이 들어가게되면 never를 도출합니다.

로 이해하고 답안 작성했습니다... infer가 처음이라 어색하네요...

```tsx
type ElementType<T> = T extends (infer U)[] ? U : never;
```

**Comment by sryung1225** [comment]
```tsx
type ElementType<T> = T extends Array<infer K>[] ? K : never;
```
입력으로 받은 `T`가 배열인지 `Array` 키워드를 이용해 확인합니다. 
배열이 아니라면 never를 반환하고 배열이라면 그 요소의 타입을 추론하도록 합니다. 추론된 타입은 `K` 입니다.

**Comment by eeeyooon** [comment]
```ts
type ElementType<T> = T extends (infer U)[] ? U : never;
```
제네릭 타입 T를 받고, T가 배열이라면 배열의 요소 타입을 추론하여 반환합니다. 만약 T가 배열이 아니라면 never 타입을 반환합니다.

**Comment by Stilllee** [comment]
```ts
// 제네릭 `Array` 타입을 사용한 표현
type ElementType<T> = T extends Array<infer U> ? U : never;

// 배열 리터럴 표현 `(infer U)[]`을 사용한 표
type ElementType<T> = T extends (infer U)[] ? U : never;
```
이 코드에서 `T extends Array<infer U>`는 `T`가 `Array<U>` 형태인지 확인합니다.

만약 `T`가 배열이면, `U`는 배열의 요소 타입을 의미하고, `infer U`는 이 배열의 요소 타입을 추론하라는 지시입니다. 따라서, `T`가 배열이면 `ElementType<T>`는 배열의 요소 타입인 `U`를 반환합니다.

반면에 `T`가 배열이 아니면, 조건문은 거짓이 되고, `never` 타입을 반환합니다. `never` 타입은 TypeScript에서 사용되는 특별한 타입으로, 여기서는 "타입이 없음"을 나타냅니다.

```ts
const numberArray = [1, 2, 3];
const stringArray = ["a", "b", "c"];

type NumberElementType = ElementType<typeof numberArray>; // 'number' 타입
type StringElementType = ElementType<typeof stringArray>; // 'string' 타입
```
- `ElementType<typeof numberArray>`는 `number[]`에 적용되므로, 결과는 `number` 타입입니다.
- `ElementType<typeof stringArray>`는 `string[]`에 적용되므로, 결과는 `string` 타입입니다.

위와같이 `infer` 키워드를 사용하여 조건부 타입을 정의하고, 배열의 요소 타입을 효율적으로 추론할 수 있습니다.
