### ISSUE TITLE
6.3_타입스크립트 컴파일러(tsc)가 소스코드를 컴파일하는 과정을 설명해주세요.

### ISSUE THREAD

**Issue by eeeyooon** [Coding-Village-Protector/woowahan-ts#15]
📝 192p

❓ 타입 스크립트 컴파일러(tsc)가 소스 코드를 컴파일하는 과정을 설명해주세요. 각 단계에서 수행되는 작업에 대해서 자세히 설명해주세요.

<br/>
<br/>

*보너스 객관식 문항 😋*

❓ 컴파일 과정 중에서 타입 스크립트가 소스가 자바스크립트 코드로 변환되기 전에 타입 검사를 수행하는 단계는 무엇인가요?

A) 바인더
B) 체커
C) 이미터
D) 파서

❓ 타입 스크립트 컴파일러가 소스 코드를 토큰으로 분리하는 단계는 무엇인가요?

A) 바인더
B) 파서
C) 스캐너
D) 이미터

**Comment by Stilllee** [comment]
#### 타입스크립트 컴파일러의 실행 과정
1. 스캐너 : 타입스크립트 소스코드를 작은 단위로 나누어 의미 있는 토큰으로 변환하는 작업을 수행한다.
2. 파서 : 스캐너가 소스 파일을 토큰으로 나눠주면 파서는 그 토큰 정보를 이용하여 AST를 생성한다.
3. 바인더 : 타입 검사를 위해 심볼이라는 데이터 구조를 생성한다.
4. 체커 : 파서가 생성한 AST와 바인더가 생성한 심볼을 활용하여 타입 검사를 수행한다.
5. 이미터 : 타입스크립트 소스를 자바스크립트(js) 파일과 타입 선언 파일(d.ts)로 생성한다.

#### 보너스 객관식 문항
1. B) 체커
2. C) 스캐너

**Comment by eeeyooon** [comment]
타입스크립트 컴파일러(tsc)는 소스코드를 컴파일하는 과정에서 여러 단계를 거칩니다.
첫 번째로, **`tsc`** 명령어가 실행되면 tsconfig.json에 명시된 옵션을 기반으로 **컴파일 과정이 시작**됩니다. 이어서, **스캐너가 코드를 읽고, 의미있는 토큰으로 분리**합니다. 다음으로, **파서가 이 토큰들을 이용하여 AST(Abstract Syntax Tree)를 생성**합니다. AST는 소스코드의 구조를 트리 형태로 표현하여 코드의 구조적 관계를 명확히 합니다. 다음 단계로 **바인더는 AST의 각 노드에 대응하는 심볼을 생성**하여 식별자 정보를 관리합니다. 이후 **체커가 AST의 노드를 탐색하면서 심볼 정보를 불러와 주어진 소스 파일에 대해 타입 검사를 수행**합니다. 이 단계에서 변수의 타입, 함수의 반환 타입 등이 검사됩니다. 마지막으로, **에러가 없다면** **이미터가 타입스크립트 AST를 자바스크립트 코드로 변환**합니다. 즉, 타입스크립트 소스를 자바스크립트 (js) 파일과 타입 선언 파일(d.ts)로 생성합니다. 
이 과정을 통해 타입스크립트는 자바스크립트 환경에서 실행될 수 있는 코드로 변환됩니다.


```
1) tsc 명령어가 실행되며 컴파일 과정이 시작됨.
2) 스캐너가 코드를 읽고, 의미 있는 토큰으로 분리함.
3) 파서가 이 토큰들을 이용하여 AST를 생성함.
4) 바인더가 AST의 각 노드에 대응하는 심볼을 생성함.
5) 체커가 AST의 노드를 탐색하며 심볼 정보를 불러와 타입 검사를 수행함.
6) 에러가 없다면 이미터가 타입스크립트 AST를 자바스크립트로 코드로 변환함.
```


*보너스 객관식 문항*

**B) 체커**
**C) 스캐너**
