### ISSUE TITLE
6.2_타입스크립트 컴파일러의 주요 역할을 설명해주세요

### ISSUE THREAD

**Issue by lulla-by** [Coding-Village-Protector/woowahan-ts#17]
📝 p187 - p191

❓ 타입스크립트 컴파일러는 크게 두 가지의 역할을 메인으로 수행합니다. 각각의 역할을 작성하고 세부적으로는 어떤 기능들을 수행하는 작성해주세요.

**Comment by sryung1225** [comment]
타입스크립트 컴파일러의 역할은 크게 2가지로 나눌 수 있습니다.

**1️⃣ 코드 검사기 역할 - 코드의 타입 오류를 검사한다.**

컴파일타임에 문법 에러와 타입 관련 에러를 모두 검출해 자바스크립트 런타임에서 발생할 수 있는 에러를 사전에 알려준다. 이 타입 검사를 거쳐 코드를 안전하게 만든 이후에는 타입스크립트 AST를 자바스크립트 코드로 변환한다.

**2️⃣ 코드 변환기 역할 - 최신 버전의 타입스크립트 코드를 구 버전의 자바스크립트로 트랜스파일한다.**

타입 검사 이후, 타입스크립트 코드를 각자의 런타임 환경에서 동작할 수 있도록 구버전의 자바스크립트로 트랜스파일한다. tsconfig.json의 compilerOptions를 이용해 변환할 자바스크립트의 버전을 특정할 수 있다.

**Comment by Stilllee** [comment]
#### 코드 검사기의 역할
타입스크립트는 컴파일타임에 문법 에러와 타입 관련 에러를 모두 검출한다.

#### 코드 변환기의 역할
타입스크립트 컴파일러는 타입을 검사한 다음 타입스크립트 코드를 각자의 런타임 환경에서 동작할 수 있도록 구버전의 자바스크립트로 트랜스파일한다.

**Comment by eeeyooon** [comment]
타입스크립트 컴파일러는 다음과 같이 두 가지 역할을 수행합니다.

첫 번째, 코드 검사기로서의 역할을 수행합니다. 컴파일 타임에 코드에 타입 오류가 없는지를 확인하여 자바스크립트 런타임에서 발생할 수 있는 문법 에러와 타입 관련 에러를 사전에 미리 검출하여 알려는 역할을 합니다.

두 번째, 코드 변환기로서의 역할을 수행합니다. 타입스크립트 컴파일러는 타입을 검사한 다음 타입스크립트 코드를 각자의 런타임 환경에서 동작할 수 있도록 구버전의 자바스크립트로 트랜스파일을 합니다. 타입스크립트 소스코드를 파싱하고 자바스크립트 코드로 변환해야 비로소 브라우저와 같은 런타임에서 실행할 수 있게 됩니다.

**Comment by lulla-by** [comment]
타입스크립트 컴파일러는 코드 검사기와 코드 변환기 두 가지의 메인 역할을 수행합니다.

첫 번째는 **코드 검사기**의 역할입니다. 
타입스크립트는 정적 언어로 런타임 이전인 컴파일 타임에 코드에 오류가 없는지 확인합니다. 따라서 js로 작성하면 런타임에서 발견되던 에러를 코드 실행하기 전에 사전 발견하여 실행 과정에서 발생할 수 있는 문제를 방지합니다. 코드 검사기로서 런타임에서 발생할 수 잇는 **문법 오류** 뿐만 아니라 **타입의 에러**도 잡아낼 수 있습니다. 타입스크립트 컴파일러는  tsc 바인더를 사용하여 타입 검사를 하며 컴파일 타임에 타입에 대한 오류를 잡아냅니다.

두 번째는 **코드 변환기**의 역할입니다. 
타입 스크립트 컴파일러는 타입을 검사한 이후 런타임에서 동작할 수 있도록 구버전의 JS코드로 변환합니다. 유사한 기능을 제공하는 바벨과의 차이점으로는 앞서 설명한 코드 검사기의 역할입니다. 바벨과 tsc 컴파일러는 모두 코드를 es5 이하의 구 버전 자바스크립트로 변환해주지만 바벨은 코드 변환기로서의 역할은 수행하지 않습니다.
