### ISSUE TITLE
7.3.2_제시한 코드의 문제 상황을 해결할 수 있는 방법에 대해 설명해주세요.

### ISSUE THREAD

**Issue by eeeyooon** [Coding-Village-Protector/woowahan-ts#20]
📝 227p

❓ 제시한 코드의 문제 상황을 해결할 수 있는 방법에 대해 설명해주세요.

```tsx

const getOrderHistory = async (page: number): Promise<History> => {
  try {
    const { data } = await axios.get(`https://some.site?page=${page}`);
    const history = await JSON.parse(data);

    return history;
  } catch (error) {
    alert(error.message);
  }
};

```

이 코드는 주문 내역을 요청할 때 에러가 발생하면 에러 메세지를 얼럿을 사용하여 사용자에게 표시해줍니다. 이때 에러 메세지를 전달해서 사용자는 어떤 에러가 발생한 건지 확인할 수 있지만 개발자 입장에서는 사용자 로그인이 만료된 건지 타임 아웃이 발생한 건지 혹은 데이터를 잘못 전달한 건지 구분할 수 없습니다.

이러한 문제를 해결하기 위해서 7장에 나온 방법들 중 어떤 방법으로 해결할 것인지 작성해주세요. 코드를 작성할 필요는 없고, 선택한 방법의 특징 관련해서 간략히 서술해주세요.

(적절한 답안을 적기 어렵다면 서브 클래싱을 활용한 방법을 선택하여, 해당 방법의 특징에 대해 설명해주세요.)

**Comment by Stilllee** [comment]
#### react-query를 활용한 에러 처리
react-query와 같은 데이터 페칭 라이브러리를 사용하면 요청에 대한 상태를 반환해주기 때문에 요청 상태를 확인하기 쉽다.
```tsx
const getOrderHistory = async (page: number) => {
  const { data } = await axios.get(`https://some.site?page=${page}`);
  return data;
};

const OrderHistoryComponent: React.FC = () => {
  const { isError, error, isLoading, data } = useQuery('orderHistory', () => getOrderHistory(1));  

  if (isError) {
    return <div>{{ error.message }가 발생했습니다.나중에 다시 시도해주세요.} </div>;
  }  

  if (isLoading) {
    return <div>로딩 중입니다.< /div>;
  } 

  return (
    <>
    {data.map((history) => (
        <div key= { history.id } > 주문 내역: { history.details } < /div>;
      ))}
    </>
  )
}
```

**Comment by lulla-by** [comment]
axios의 interceptors를 사용하고 싶습니다. api 응답을 받은 후 에러 발생시 실행시키는 함수에서 에러의 status를 기준으로 에러들을 나누는 분기처리를 진행하여 에러를 핸들링할것입니다.

또한 axios interceptors 를 활용하면 바디에 담겨오는 코드를 기준으로 에러여부를 판단할 수 있기 때문에 200번대로 오는 커스텀 에러를 api 응답 이후 성공시에 호출하는 함수에서 분기를 나눠 커스텀 에러도 핸들링 할 수 있기에 interceptors 기능을 사용하고 싶습니다

**Comment by eeeyooon** [comment]
위 문제를 해결하는 방법은 다양합니다. 그 중 3가지 방법에 대해 설명하겠습니다.


<br/>

1️⃣ 서브 클래싱
에러 서브클래싱을 통해 특정 에러에 대한 타입과 상세한 정보를 개발자에게 전달할 수 있습니다. 서브클래싱을 활용하면 각각의 상황에 맞게 에러 클래스를 정의하여 에러의 타입을 명확하게 확인할 수 있습니다. 이를 통해 로그인 만료, 타임아웃, 데이터 전달 오류 등에 대한 구체적인 정보를 제공할 수 있습니다.



2️⃣ superstruct를 사용한 방법
superstruct를 활용하여 응답의 상태 코드와 메시지를 구조화하고 검증할 수 있습니다. 예를 들어, 응답 데이터의 구조를 명시적으로 정의하고, validate 함수를 사용하여 해당 구조에 맞는지 확인합니다. 이를 통해 개발자는 상태 코드와 메시지를 포함한 구조화된 에러 객체를 받아 처리할 수 있습니다.



3️⃣ axios 인터셉터 활용
axios를 사용하여 api처리를 하고 있다면 axios 인터셉터를 활용하는 방안도 있습니다. axios 인터셉터를 활용하면 모든 API 호출에 대한 일괄적인 에러 처리 로직을 구현할 수 있습니다. 인터셉터를 사용하여 응답에서 상태 코드와 메시지를 추출하고, 개발자에게 전달할 수 있습니다. 이를 통해 중앙에서 에러 처리 로직을 관리하면서 코드의 중복을 줄일 수 있습니다.

<br/>




이 외에도 다양한 방법으로 에러 타입과 정보를 명시하여, 개발자에게 전달할 수 있습니다. 그 방법에는 에러 바운더리, redux나 react-query와 같은 상태 관리 라이브러리도 포함됩니다. 

💡 다만, 에러 바운더리나 상태 관리 라이브러리는 주로 전반적인 에러 관리와 상태 관리에 활용되는 경향이 있으므로 주어진 문제와 같이 특정 API 호출에서 발생하는 에러에 대한 처리를 간단하게 하기 위해선 서브 클래싱이나 superstruct와 같은 간단한 방법들이 더 적절할 수 있습니다.
