### ISSUE TITLE
9.1.0_함수형 컴포넌트에서 클래스형 컴포넌트의 역할을 수행하는 훅들은 무엇인가요?

### ISSUE THREAD

**Issue by lulla-by** [Coding-Village-Protector/woowahan-ts#28]
📝 p287

❓ 클래스형 컴포넌트에서 제공하는 기능을 리액트 훅의 도입으로 함수형 컴포넌트에서도 다룰 수 있게 되었는데요.
기존 클래스형 컴포넌트에서 제공하던 기능들의 역할을 하는 리액트 훅을 밑에 제시된 설명과 매치하여 작성해주세요.

A. 컴포넌트의 생명주기와 관련된 작업을 수행하는 훅
B. 특정한 비즈니스 로직을 재사용하기 위해 사용자가 만들 수 있는 훅
C. 사이드 이펙트를 다루기 위해 사용되는 훅
D. 컴포넌트 내에서 상태를 추가하고 관리하는 데 사용되는 훅

**Comment by Stilllee** [comment]
A : `useEffect`
B : 커스텀 훅
C : `useEffect`
D : `useState`

**Comment by eeeyooon** [comment]
A. useEffect, useLayoutEffect
B. Custom Hook
C. useEffect
D. useState

**Comment by sryung1225** [comment]
A. `useEffect` `useLayoutEffect`
B. custom hook
C. `useEffect`
D. `useState`

**Comment by lulla-by** [comment]
A: `useEffect`
B: 커스텀 훅
C:`useEffect`
D:`useState`
