### ISSUE TITLE
10.1.2 useReducer에 대하여

### ISSUE THREAD

**Issue by Stilllee** [Coding-Village-Protector/woowahan-ts#31]
📝 313p

❓ useReducer 퀴즈

#### 1. `useRedecer`훅은 어떤 경우에 `useState`보다 더 적합할까?
A. 간단한 문자열 상태를 관리할 때
B. 복잡한 상태 로직을 다룰 때, 특히 다수의 하위 필드를 포함하는 경우
C. 상태 관리가 필요하지 않은 경우
<br>

#### 2. `useReducer`가 특히 유용한 상황은 다음 상태가 이전 상태에 어떤 의존성을 가질 때이다.
A. O
B. X
<br>

#### 3. `useReducer`를 사용할 때, 액션을 정의하고 이 액션을 어떻게 처리할지는 어디에서 결정할까?
A. `dispatch` 함수
B. `reducer` 함수
C. `useState` 훅
<br>

#### 4. `useReducer`를 사용하는 주된 이점 중 하나는 복잡한 상태 로직을 숨기고 안전성을 높이는 것이다. 
A. O
B. X

**Comment by sryung1225** [comment]
(1) B. 복잡한 상태 로직을 다룰 때, 특히 다수의 하위 필드를 포함하는 경우
(2) A. O
(3) B. `reducer` 함수
(4) A. O

**Comment by eeeyooon** [comment]
1. B
2. A
3. B
4. A

**Comment by Stilllee** [comment]
### 1. B, 복잡한 상태 로직을 다룰 때, 특히 다수의 하위 필드를 포함하는 경우
`useState`는 단순한 상태 관리에 적합하지만, 복잡한 상태 로직이나 상태가 여러 하위 필드를 포함하는 경우에는 `useReducer`가 더 적합합니다. 

`useReducer`는 상태 업데이트 로직을 컴포넌트 밖으로 분리시킬 수 있어 복잡한 상태를 더 효율적으로 관리할 수 있습니다.
<br>

### 2. A, `useReducer`는 이전 상태에 의존적인 상태 업데이트에 매우 유용하다.
`reducer` 함수는 현재 상태와 액션을 인자로 받아 새로운 상태를 반환합니다. 이를 통해 이전 상태에 기반하여 새 상태를 생성하는 복잡한 로직을 관리할 수 있습니다.
<br>

### 3. B, `useReducer`에서 액션을 처리하는 로직은 `reducer` 함수에서 정의된다.
`reducer` 함수는 액션의 타입에 따라 상태를 어떻게 변경할지 결정합니다. 

`dispatch` 함수는 액션을 발생시키는 역할을 하지만, 액션의 처리 방식은 `reducer`에서 정의됩니다.
<br>

### 4. A, `useReducer`는 복잡한 상태 관리 로직을 숨기고 안전성과 가독성을 높인다.
`useReducer`는 복잡한 상태 관리 로직을 컴포넌트 외부의 `reducer` 함수에 숨김으로써 코드의 안전성과 가독성을 높일 수 있습니다. 상태 업데이트 로직을 분리함으로써 컴포넌트의 복잡성을 줄이고, 코드를 더 관리하기 쉽게 만들 수 있습니다.
