### ISSUE TITLE
10.1.3_전역 상태를 관리하는 각 수단의 장단점을 서술하세요.

### ISSUE THREAD

**Issue by sryung1225** [Coding-Village-Protector/woowahan-ts#33]
📝 p316

❓ 전역 상태를 관리하는 수단 3가지를 골라 각각의 장단점을 서술해주세요.

상태를 여러 컴포넌트와 공유하기 위해서 **전역 상태(Global State)** 를 사용합니다. 책에서 소개하는 전역 상태를 사용하는 수단은 크게 5가지로, 리액트 **Context API**와 외부 상태 라이브러리 **MobX**, **Redux**, **Recoil**, **Zustand** 가 그 예시입니다.

이 중 **3가지**를 선택하여 각 수단의 **장단점**을 서술해주세요.

(선택 기준은 사용 경험이 있는 것을 최우선으로 하며, 그 외 평소 관심이 있었거나 인기 있는 수단을 고릅니다.) 
(필요 시 책에서 제시되지 않은 외부 상태 관리 라이브러리(ex. Jotai)에 대한 서술도 허용합니다.)

**Comment by Stilllee** [comment]
### Context API
#### 장점
- 깊은 레벨의 컴포넌트 간 데이터 전달 문제(Prop Drilling)를 해결한다.
- 전역적으로 데이터를 관리하고, 여러 컴포넌트에 걸쳐 props를 효율적으로 전달할 수 있다.
#### 단점
- 컨텍스트 프로바이더의 props로 주입된 값이나 참조가 변경될 때마다 해당 컨텍스트를 구독하고 있는 모든 컴포넌트가 리렌더링되기 때문에 대규모 애플리케이션이나 성능이 중요한 애플리케이션에서는 권장되지 않는다.
<br>

### Recoil
#### 장점
- 보일러플레이트가 적고 난이도가 쉬워 배우기 쉽다.
- React의 훅과 잘 통합되어 있어 React 개발자들에게 친숙하며, React의 기능을 최대한 활용할 수 있다.
- Atom과 Selector라는 개념을 통해 세밀한 상태 관리를 할 수 있으며, 파생된 상태를 관리하는데 유용하다.
#### 단점
- 라이브러리가 실험적인 상태이기 때문에 다양한 요구 사항에 대한 충분한 검증이 이루어지지 않았다.
- 새로운 버전의 릴리즈 주기가 다른 유사 라이브러리에 비해 느린 편이며, issue 및 PR에 대한 공식 코멘트가 없는 등 관리가 되지 않고 있다.
<br>

### Zustand
#### 장점
- 간결하고 사용하기 쉬운 API를 제공하며, 많은 보일러플레이트를 요구하지 않는다.
- 클로저를 사용하여 스토어 내부의 상태를 관리하기 떄문에 특정 라이브러리에 종속되지 않고 유연하게 사용될 수 있다.
- 상태 관리 로직을 캡슐화하고, 생성된 훅을 어느 컴포넌트에서나 임포트하여 사용할 수 있어 코드 재사용성과 유지보수성을 높여준다.
#### 단점
- Zustand는 여전히 상대적으로 새로운 라이브러리이기 때문에, 커뮤니티의 지원이나 사용 사례가 Redux나 MobX에 비해 제한적일 수 있다.

**Comment by lulla-by** [comment]
### Redux

✔장점: 오랜 기간 사용되어 충분히 검증받음, 상태 변경 추적에 최적화 되어 있어 오류 발생 시 해결하기 용이함

❌단점:  많은 보일러플레이트, 초반에 진입하기에 난이도가 높다.

### Recoil

✔장점:  적은 보일러플레이트, 낮은 난이도

❌단점: 아직 실험적인 상태로 충분한 검증이 필요함

### zustand

✔장점: 적은 보일러플레이트, 같은 Flux 패턴인 redux에 비해 사용하기 쉽다. 난이도가 낮음.

❌단점: 리코일과 마찬가지로 아직 작은 규모라 에러 발생 시 Redux같은 라이브러리에 비해서는 에러를 해결하기 위한 리소스를 발견하기 어려울 수 있음.


**개인적으로는 Redux를 선호하는 편입니다.** Recoil도 프로젝트에서 사용해보고 zustand도 잠깐 공부해봤는데 보일러 플레이트가 적어서 세팅하기 수월하고 코드도 간단해서 편하긴 하지만 아무래도 리소스나 에러 추적등은 Redux가 더 좋더라구요. 물론 초반에 진입장벽이 있지만 Redux-tookit을 사용하면 조금(?) 수월해져서 좋은것 같아요!

**Comment by eeeyooon** [comment]
### context API

context API는 react에 내장된 기능으로, props를 사용하지 않아도 특정 값이 필요한 컴포넌트끼리 쉽게 값을 공유할 수 있게 해줍니다.

장점

- 추가 라이브러리 없이 React만으로 전역 상태 관리가 가능합니다.
- React에 내장되어 있어 외부 라이브러리와의 호환성 문제가 적습니다.

단점

- Context API는 Provider 하위의 모든 consumer들이 Provider 속성이 변경될 때마다 다시 렌더링됩니다. 만약 Proveder의 값이 배열이나 객체인 경우, 조금이라도 변경된다면 그 Context를 구독하고 있는 하위의 모든 컴포넌트가 다시 렌더린되어 불필요한 렌더링이 발생할 수 있습니다.
- 새로운 `Provider`를 하위에 추가하는 방법도 있지만, `Provider`를 새로 추가하면 하위의 모든 요소들이 다시 마운트됩니다. (`마운트 : 컴포넌트가 생성되고 브라우저에 나타나는 것`)
- 결론적으로, tree 구조의 단점인 props drillilng 해결을 위해 사용하지만, 상위에 `Provider`가 추가된 tree 구조가 됩니다.

### Redux

장점

- redux의 큰 특징 중 하나는 reducer는 순수 함수라는 점이다. 이는 함수형 프로그래밍의 장점을 상속받아 테스트가 가능하게 하고, 함수의 동작을 예측하기 쉽게 합니다.
- 비동기 작업, 로깅, 크래시 리포팅 등 다양한 미들웨어를 지원합니다.

단점

- 개념을 이해하기까지 시간이 많이 필요하며 러닝커브가 분명히 존재합니다.

### Recoil

Recoil은 React를 위한 상태 관리 라이브러리로, atoms에서 selectors를 거쳐 React 컴포넌트로 내려가는 data flow graph를 생성합니다.

장점

- React 문법 친화적입니다. 전역 상태 값도 React의 state처럼 간단한 get/set 인터페이스로 사용할 수 있는 boilerplate-free API를 제공합니다.
- 동시성 모드를 비롯한 다른 새로운 React의 기능들과의 호환 가능성도 가집니다.
- 추가 라이브러리없이 Recoil만으로 비동기 처리를 간단하게 할 수 있습니다.
- 동일한 atom 값에 대해 내부적으로 메모이즈된 값을 반환하여 속도가 빠릅니다.

단점

- 리덕스의 devtools만큼 훌륭한 디버깅툴이 아직 존재하지 않습니다.
- 관련 오픈 소스 생태계가 redux에 비해서 부족합니다.

**Comment by sryung1225** [comment]
### Context API

전역적으로 공유해야 하는 데이터를 컨텍스트로 제공하고 해당 컨텍스트를 구독한 컴포넌트에서만 데이터를 읽도록 허용합니다.. Context API 자체는 엄밀히 말하면 전역 상태를 관리하기 위한 솔루션은 아니지만 `useState` 나 `useReducer` 같이 지역 상태를 관리하는 API와 결합해 여러 컴포넌트 사이에서 상태를 공유합니다.

😍 장점
- 따로 라이브러리를 설치하지 않기 때문에 사용이 편합니다.

🤢 단점
- Provider가 공유하는 prop의 값이나 참조가 변경될 때, 해당 컨텍스트를 구독하고 있는 모든 컴포넌트가 리렌더링되기 때문에 불필요한 리렌더링이 생겨납니다.
- 대규모거나 성능이 중요한 애플리케이션에서는 권장되지 않습니다.

### MobX

객체 지향 프로그래밍과 반응형 프로그래밍 패러다임의 영향을 받은 라이브러리입니다. 상태 변경 로직을 단순하게 작성할 수 있고, 복잡한 업데이트 로직을 라이브러리에 위임할 수 있습니다.

😍 장점

- 객체 지향 스타일로 코드를 작성하는 데 익숙하다면 편하게 사용할 수 있습니다. (ex. 서버 개발자)

🤢 단점

- 데이터가 언제, 어떻게 변하는지 추적하기 어렵기 때문에 트러블 슈팅에 어려움을 겪을 수 있습니다.  (상태 변경 시 다수의 store가 영향을 받습니다.)
- 클래스 형태가 자바스크립트와 어울리지 않는다 느낄 수 있습니다.

### Redux

함수형 프로그래밍의 영향을 받은 라이브러리입니다. 특정 UI 프레임워크에 종속되어있지 않아 독립적으로 상태 관리 라이브러리를 사용할 수 있습니다.

😍 장점

- 오랜 기간 사용되어 왔기 때문에 다양한 요구 사항에 대해 충분히 검증됐고 레퍼런스가 풍부합니다.
- 상태 변경 추적에 최적화되어 있어, 특정 상황에서 발생한 애플리케이션 문제의 원인을 파악하는 데 용이합니다.
- 사용을 돕는 Toolkit이 존재합니다.

🤢 단점

- 단순한 상태 설정에도 많은 보일러플레이트가 필요하고(action, reducer, selector, store), 사용 난도가 높습니다.
- 작업 당 작성 필요한 부분이 많아 소규모 프로젝트에 적용하기에는 적합하지 않습니다.

### Recoil

상태를 저장할 수 있는 Atom과 해당 상태를 변형할 수 있는 순수 함수 selector를 통해 상태를 관리하는 라이브러리입니다.

😍 장점

- 보일러플레이트가 적고 난이도가 쉬워 배우기 쉽습니다.
- useState와 비슷하게 사용하기 때문에 직관적입니다. React 사용자가 쉽게 익숙해질 수 있습니다.

🤢 단점

- 라이브러리가 아직 실험적인 상태이기 때문에 다양한 요구 사항에 대한 충분한 검증이 이루어지지 않았습니다.
- DevTools가 완전치 않아 디버깅에 번거로움이 있습니다.
- 23년 4월 이후로 업데이트되고 있지 않습니다.

### Zustand

Flux 패턴을 사용하며 많은 보일러플레이트를 가지지 않는 훅 기반의 편리한 API 모듈을 제공합니다. 클로저를 활용하여 스토어 내부 상태를 관리함으로써 특정 라이브러리에 종속되지 않는 특징이 있습니다.

😍 장점
- 보일러플레이트가 적고 난이도가 쉽습니다.

🤢 단점

- 커뮤니티가 아직 활성화되지 않아 한글 학습 자료가 적습니다.
