### ISSUE TITLE
12.1.1_앰비언트 타입 선언은 어떻게 활용되는지 사례를 들어 설명해주세요.

### ISSUE THREAD

**Issue by eeeyooon** [Coding-Village-Protector/woowahan-ts#36]
📝 338p

값을 포함하는 일반적인 선언과 구별하기 위해 .d ts 확장자를 가진 파일에서 하는 타입 선언을 앰비언트(ambient) 타입 선언이라고 부릅니다. 

❓ 앰비언트 타입 선언은 어떻게 활용되는지 사례를 들어 설명해주세요.

❓ 앰비언트 타입 선언을 위해 사용되는 키워드는 무엇인가요?

**Comment by sryung1225** [comment]
👉 자바스크립트로 작성된 npm 라이브러리 타입 선언을 위해 사용됩니다. 
기본적으로는 any로 추론될텐데 만일 tsconfig.json에서 any를 사용하지 못하게 설정했다면(`"noImplicityAny": false`) 프로젝트가 제대로 빌드되지 않게 됩니다. 이런 경우를 대비해 자바스크립트 라이브러리 내부 함수와 변수의 타입을 앰비언트 타입으로 선언합니다. 이 앰비언트 타입을 보고 타입스크립트는 자동으로 .d.ts 파일을 검색하여 타입 검사를 진행하고 문제없이 컴파일 됩니다.

👉 앰비언트 타입 선언을 위해 `declare` 키워드를 사용합니다.

**Comment by lulla-by** [comment]
✅ `.js`, `.ts` 확장자가 아닌 파일을 임포트할 경우 에러가 발생할 수 있는데 이런 상황에서 `declare` 를 사용하여 앰비언트 선언을 진행하면 이미 존재하지만 타입스크립트가 알지 못하는 부분을 컴파일러에 알려주어 에러를 발생하지 않게 됩니다.

예를 들면 `png`등 이미지 파일을 모듈로 임포트할 경우 다음과 같이 선언하여 에러를 방지할 수 있습니다.

```tsx
declare module "*png"{
  const src:string;
  export default src;
}
```

✅ 앰비언트 타입 선언시에는  `declare` 키워드를 사용합니다.

**Comment by eeeyooon** [comment]
**자바스크립트로 작성된 라이브러리**

자바스크립트 라이브러리 내부 함수와 변수의 타입을 앰비언트 타입으로 선언하면 타입스크립트는 자동으로 .d.ts파일을 해석해 코드를 작성할 때 유용한 타입 힌트를 제공합니다.

<br/>

**타입스크립트로 작성된 라이브러리**

타입스크립트 파일을 직접 배포하여 라이브러리 사용자가 타입스크립트를 컴파일 할 때 라이브러리 코드도 함께 컴파일하게 할 수도 있습니다. 그러나 자바스크립트 파일과 .d.ts 파일로 배포하면 라이브러리 코드를 따로 컴파일하지 않아도 되기 때문에 컴파일 시간이 크게 줄어듭니다.

<br/>

**자바스크립트 어딘가에 전역변수가 정의되어 있음을 타입스크립트에 알릴 때**

타입스크립트로 직접 구현하지 않았지만 실제 자바스크립트 어딘가에 전역 변수가 정의되어 있는 상황을 타입스크립트에 알릴 때 앰비언트 타입 선언을 사용합니다.

<br/>

-------- 

`declare`
