### ISSUE TITLE
12.1.3_앰비언트 타입 선언을 잘못 사용할 경우 생길 수 있는 문제점은 무엇인가요?

### ISSUE THREAD

**Issue by lulla-by** [Coding-Village-Protector/woowahan-ts#38]
📝 p 341

❓ `.d.ts`를 가진 파일에서 하는 타입 선언을 앰비언트 타입 선언이라고 하는데요. 이러한 앰비언트 타입 선언을 하게 되면 어딘가에 해당 자바스크립트 값이 존재함을 선언하게 되어 전역적인 의미를 지니게 됩니다.  이와 연관 시켜 앰비언트 타입 선언을 잘못 사용할 경우 생길 수 있는 문제점은 무엇일지 간략하게 설명해주세요.

**Comment by Stilllee** [comment]
#### 1. 전역 범위의 오염
앰비언트 타입 선언은 전역 범위에 영향을 미치며, 이로 인해 프로젝트 전반에 걸쳐 의도치 않은 영향을 줄 수 있습니다. 

예를 들어, 하나의 파일에서 선언된 앰비언트 타입이 다른 파일에서도 영향을 미치게 되어 혼란을 야기할 수 있습니다.
<br>

#### 2. 의존성 관리의 어려움
앰비언트 타입은 명시적인 `import`나 `export`가 없이 전역적으로 사용됩니다. 

이 때문에 코드의 의존성 관계가 명확하지 않아, 어떤 타입이 어디서 정의되었는지 추적하기 어렵고 이는 프로젝트의 유지보수를 어렵게 만듭니다.
<br>

#### 3. 충돌 및 혼란
서로 다른 파일 또는 라이브러리에서 같은 이름으로 앰비언트 타입을 선언할 경우, 이들 간의 충돌이 발생할 수 있습니다. 

이는 예상치 못한 버그를 유발하고, 어떤 선언이 실제로 적용되는지 파악하기 어렵게 만듭니다.
<br>

#### 4. 유지보수의 복잡성
앰비언트 타입 선언이 프로젝트의 여러 곳에서 이루어질 경우, 특히 큰 프로젝트에서는 이러한 선언들을 관리하고 추적하는 것이 매우 복잡해집니다.

**Comment by sryung1225** [comment]
앰비언트 타입은 명시적인 import나 export 없이도 코드 전역에서 사용할 수 있다는 점에서 일반 타입 선언과 섞이게 되면 앰비언트 선언이 어떤 파일에 포함되어 있는지 파악하기 어려워지는 문제가 있습니다. 때문에 앰비언트 타입 선언을 .d.ts 파일 내에서 하는 것이 일종의 개발자 간 약속으로 자리 잡고 있습니다.

**Comment by eeeyooon** [comment]
앰비언트 타입은 명시적인 임포트나 익스포트 없이 코드 전역에서 사용할 수 있습니다. 그래서, .ts 파일 내부에 앰비언트 변수를 선언할 때 앰비언트 타입의 의존성 관계가 보이지 않기 때문에 변경에 의한 영향 범위를 파악하기 어렵습니다. 특히 소스코드 규모가 크다면 추후 변경이 어려워질 수 있습니다. 
앰비언트 변수 선언은 어느 곳에나 영향을 줄 수 있기 때문에 일반 타입 선언과 섞이게 되면 앰비언트 선언이 어떤 파일에 포함되어 있는지 파악하기 어려워집니다. .d.ts 확장자 파일 내에서 앰비언트 타입 선언을 하는 것은 일종의 개발자 간 약속으로, 가독성과 유지보수성을 위해 타입 선언 위치를 명확히 하는 것이 중요합니다.

**Comment by lulla-by** [comment]
`declare` 키워드를 사용하여 선언하는 앰비언트 타입 선언은 `.d.ts`뿐만 아니라  `.ts`, `.tsx`확장자에서도 사용 가능합니다. 따라서 작은 컴포넌트에서 선언한 앰비언트 역시 어느 곳에나 영향을 줄 수 있습니다. 이처럼 앰비언트 타입 선언은 모든 파일에 영향을 주기 때문에 무분별하게 사용하게 되면 어떤 파일에서 해당 앰비언트 타입이 포함된 것인지 파악하기 어려워져 의존성에 문제가 생길 수 있으며, 해당 변수의 영향 범위를 파악하기 어려워져 개발자에게 혼란을 야기할 수 있습니다. 

또한, 서로 다른 라이브러리에서 동일한 이름의 앰비언트 타입이 선언된다면 충돌이 발생하여 어떤 타입 선언이 적용될 지 알기 어려워지며 의도한 동작대로 동작하지 않을 수 있습니다
