### ISSUE TITLE
13.1_객체 지향 관점에서 타입스크립트의 이점을 서술하세요

### ISSUE THREAD

**Issue by sryung1225** [Coding-Village-Protector/woowahan-ts#41]
📝 p365
❓ TypeScript를 활용하면 프론트엔드에서 객체 지향을 구현할 수 있습니다. 컴포넌트를 조합하는 것도 객체 지향을 활용하는 것이기 때문에 컴포넌트를 개발하는 것이 사실상 객체 지향을 구현하고 있다고 말할 수 있습니다. 

그렇다면 **객체 지향 관점에서 TypeScript가 프론트엔드에 주는 이점**에 대해 서술해주세요.

**Comment by eeeyooon** [comment]
1. 타입스크립트로 DI (의존성 주입) 패턴을 더욱 명확하게 표현할 수 있습니다.
타입스크립트는 객체 자체가 아니라 프레임워크에 의해 객체의 의존성이 주입되는 DI 패턴을 따르는데, DI 패턴을 따르면 객체 간의 결합도를 낮출 수 있습니다.

2. 타입스크립트는 점진적 타이핑, 구조적 타이핑, 덕 타이핑을 결합한 언어로 객체 지향의 폭을 넓혀줍니다. 
타입스크립트 자체가 객체 지향적으로 다양한 측면을 표현하는 데 큰 장점을 가지고 있습니다.

**Comment by lulla-by** [comment]
1) 타입스크립트는 DI패턴을 더욱 명확하게 표현하여 객체간의 결합도를 낮출 수 있습니다.

2) 타입스크립트는 점진적 타이핑, 구조적 타이핑, 덕 타이핑을 결합한 언어로 객체 지향의 폭을 넓혀줍니다.

**Comment by Stilllee** [comment]
- **명확한 의존성 주입(Dependency Injection) 표현** : 
인터페이스를 사용하여 컴포넌트 간의 협력 관계를 명확하게 정의할 수 있으며, 이를 통해 객체 간의 결합도를 낮출 수 있습니다.

- **객체 지향적 표현의 다양성** : 
타입스크립트는 점진적, 구조적, 덕 타이핑을 결합한 언어로서 객체 지향의 폭을 넓혀, 리액트와 같은 라이브러리에서 컴포넌트와 상태 관리를 객체 지향적으로 접근할 수 있게 합니다.

**Comment by sryung1225** [comment]
1. **DI 패턴을 명확하게 표현할 수 있게 돕습니다.**
TypeScript는 객체 자체가 아니라 컴포넌트에 의해 객체의 의존성이 주입되는 DI(Dependency Injection. 의존성 주입) 패턴을 따르시 때문에 이러한 DI 패턴을 더욱 명확하게 표현할 수 있게 해줍니다.
    
2. **객제 지향의 폭을 넓혀줍니다.**
TypeScript 자체가 점진적 타이핑+구조적 타이핑+덕 타이핑가 결합한 언어이기 때문에 객체 지향적으로 다양한 측면을 표현하는 데 큰 장점을 가집니다.
