### ISSUE TITLE
13.1_ 자바스크립트에 비해 타입스크립트가 객체 지향을 온전히 구현할 수 있는 이유는 무엇인가요?

### ISSUE THREAD

**Issue by lulla-by** [Coding-Village-Protector/woowahan-ts#42]
📝 p364

❓ 자바스크립트에 비해 타입스크립트가 객체 지향을 온전히 구현하는데 더 유리한 이유는 무엇인가요?

**Comment by sryung1225** [comment]
JavaScript는 전통적인 객체 지향 프로그래밍 언어에서 기대할 수 있는 일부 기능을 지원하지 않아 객체 지향을 온전히 구현하는 데 부족함이 있습니다. 반면 **TypeScript는 이러한 제약을 해결할 수 있는 private와 같은 접근 제어자, 추상 클래스, 추상 메서드 등을 지원**하기 때문에 객체 지향을 구현할 수 있도록 도와주는 자바스크립의 슈퍼셋으로 볼 수 있습니다.

그리고 **TypeScript는 점진적 타이핑 + 구조적 타이핑 + 덕 타이핑이 결합된 언어**로서 객체 지향의 폭을 넓혀줍니다.
- 점진적 타이핑 : 컴파일 타임에 타입을 검사하면서 필요에 따라 타입 선언은 생략
- 구조적 타이핑 : 구조로 타입을 구분
- 덕 타이핑 : 어떤 타입에 부합되는 변수와 메서드를 가지는지에 따라 타입을 결정

**Comment by eeeyooon** [comment]
자바스크립트는 전통적인 객체 지향 프로그래밍 언어에서 기대할 수 있는 일부 기능을 지원하지 않아 객체 지향을 온전히 구현하기가 어렵습니다. 이러한 제약을 타입스크립트는 private과 같은 접근 제어자나 추상 클래스, 추상 메서드 같은 기능을 지원하면서 해결합니다. 타입스크립트는 객체 지향을 구현할 수 있도록 도와주는 자바스크립트의 슈퍼셋으로 볼 수 있습니다. 
타입스크립트는 점진적 타이핑, 구조적 타이핑 그리고 덕 타이핑이 결합한 언어로 이 언어의 특징들이 객체 지향의 폭을 넓혀줍니다.
타입스크립트를 사용함으로써, 우리는 객체지향을 자바스크립트보다 더 쉽게 표현할 수 있고 복잡한 비즈니스 로직을 타입스크립트로 좀 더 수월하게 구현할 수 있게 되었습니다.

**Comment by lulla-by** [comment]
자바스크립트에서도 객체 지향 프로그래밍을 할 수 있지만. 자바스크립트는 프로토타입 기반의 객체 지향 언어로 객체 지향 프로그래밍을 할 수 있습니다. 하지만 전통적인 객체 지향 프로그래밍 언어에서 기대할 수 있는 일부의 기능을 제공하지 않아 온전한 객체 지향 구현은 어렵습니다.

이러한 제약을 typescript가 접근  제어자나 추상 클래스, 추상 메서드 같은 기능을 지원해주며 해결됩니다.

또한 타입스크립트는 점진적 타이핑, 구조적 타이핑, 덕타이핑이 결합한 언어로 이것들을 한데 모아 객체 지향의 폭을 넓혀줍니다.
