### ISSUE TITLE
4.2_타입가드의 종류에는 무엇이 있으며 각각 어떤 상황에서 사용하나요?

### ISSUE THREAD

**Issue by lulla-by** [Coding-Village-Protector/woowahan-ts#9]
📝 132 - 138

❓ 타입가드는 변수 또는 표현식의 타입 범위를 좁혀나가 더 정확하고 명시적인 타입 추론을 가능하게 하며 복잡한 타입을 작은 타입으로 축소하여 타입의 안전성을 높일 수 있습니다. 

이러한 타입가드는 대표적으로 **자바스크립트 연산자**를 사용한 타입가드와 **사용자 정의** 타입가드로 나뉘는데요. 

**자바스크립트 연산자**를 이용한 **3가지**의 대표적인 **타입가드 연산자**와 **사용자 정의** **타입가드**를 사용하는 **연산자**를  말해주세요. 

그리고 각각의 연산자는 어떤 상황에서 사용이 되는지 간단하게 설명해주세요.

**Comment by Stilllee** [comment]
## 자바스크립트 연산자를 활용한 타입가드
런타임에 유효한 타입 가드를 만들기 위해 사용한다.
### 1. typeof
원시 타입을 추론할 때 사용한다.

<details>
  <summary>예시</summary>

  ```ts
let x: any = "Hello TypeScript!";

if (typeof x === "string") {
  console.log(x); // "Hello TypeScript!"
} else {
  console.log("x is not a string");
};
```
</details>
<br>

### 2. instanceof
인스턴스화된 객체 타입을 판별할 때 사용한다.

<details>
  <summary>예시</summary>

  ```ts
class MyClass {}

let x: any = new MyClass();

if (x instanceof MyClass) {
  console.log(x); 
} else {
  console.log("x is not an instance of MyClass");
};
```
</details>
<br>

### 3. in
객체의 속성이 있는지 없는지에 따른 구분할 때 사용한다.

<details>
  <summary>예시</summary>

  ```ts
let protector = { name: "철수", mbti: 'ESTJ'};

if ("mbti" in protector) {
  console.log(`방범대원 ${protector.name}의 MBTI는 ${protector.mbti}입니다.`); 
  // "방범대원 철수의 MBTI는 ESTJ입니다."
} else {
  console.log("mbti does not exist in protector");
};
```
</details>
<br>

## 사용자 정의 타입가드
사용자가 직접 어떤 타입으로 값을 좁힐지를 직접 지정하는 방식이다.
### is 연산자를 활용한 예시

<details>
  <summary>예시</summary>

  ```ts
function isNumber(value: any): value is number {
    return typeof value === 'number';
}

let myValue: any = 5;

if (isNumber(myValue)) {
    console.log('myValue is a number'); // 출력
} else {
    console.log('myValue is not a number');
};

myValue = 'five';

if (isNumber(myValue)) {
    console.log('myValue is a number');
} else {
    console.log('myValue is not a number'); // 출력
};
```
</details>

**Comment by eeeyooon** [comment]
타입 가드로 활용하는 자바스크립트 연산자로는 원시 타입을 추론할 때 주로 쓰이는 `typeof` 연산자, 인스턴스화된 객체 타입을 판별할 때 쓰이는 `instanceof` 연산자, 객체의 속성이 있는지 없는지에 따라 구분할 때 쓰이는 `in` 연산자가 있습니다.

사용자가 직접 어떤 타입으로 값을 좁힐지를 지정할 때 `is` 연산자로 타입 명제인 함수를 정의합니다.

**Comment by sryung1225** [comment]
자바스크립트 연산자를 이용한 3가지 대표적인 타입가드 연산자
- `typeof` : 원시타입을 추론할 때 사용
- `instance of` : typeof의 한계와 연관되며 인스턴스화된 객체 타입을 판별할 때 사용
- `in`: 객체의 속성이 들어있는지 여부에 따라 구분할 때 사용

사용자정의 타입가드를 이용하는 연산자
- `is`: 직접 어떤 타입으로 값을 좁힐지 지정하는 데에 사용
